### PR TITLE
Pcf 54

### PR DESCRIPTION
**Pull request by corbin-chris**
**21st November 2022: Pre-review information**
**Summary**
This app runs STAR-Fusion, a tool which identifies candidate fusion transcripts from RNA alignments. This app is specifically set up to process the 'Chimeric.out.junction' files produced by the earlier STAR-Aligner alignment step. It produces files of candidate fusion regions.

**Changes from last pull request**
Minor changes made from main branch:
- CPU argument now runs with number of threads from instance information
- Junction files taken as input can end either out.junction or junction.out
- More-extensive STAR-Fusion parameters can be passed as a string

**Demonstration**
I made a project to run the example in: project-GJqqBK04JkPBQyJ6PjybFypx
The app was run in the following job:
https://platform.dnanexus.com/projects/GJqqBK04JkPBQyJ6PjybFypx/monitor/job/GJxZQ204JkP0XZBJ0ZJVjZ14

Using this applet (though NB this gets overwritten when changes are made):
applet-GJxZ93j4JkP1GPZ82GG46yXY

First I had to rename an example junctions file to give it a sample name:
`dx select project-GJqqBK04JkPBQyJ6PjybFypx
dx cp project-GFfV0qQ42QQVf6VX12zxxvx3:file-GJJPZvQ42QQQpjzX90Z3ZG1b Matt-2-7-2b.chimeric.junction.out
ID: file-GJJPZvQ42QQQpjzX90Z3ZG1b
`

The app was then run as follows:
`dx run project-GJqqBK04JkPBQyJ6PjybFypx:/eggd_starfusion \
-ijunction=file-GJJPZvQ42QQQpjzX90Z3ZG1b \
-isf_docker=file-GGygFkQ4Y6Yjp0jpBjgV9VZx \
-igenome_lib=file-GFq2PJ846G2F120Y80qFVJQb
`

It produced the following output files (found in project-GJqqBK04JkPBQyJ6PjybFypx):
file-GJxbF184F6bZ7pgx1bbKzVk9: Matt-2-7-2b.star-fusion.fusion_predictions.abridged.tsv
file-GJxbF184F6bbj5FF1qq6gGYv: Matt-2-7-2b.star-fusion.fusion_predictions.tsv

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/2)

### CODE REVIEW

**Review by kjwinfield — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/2)* status: all files reviewed, 3 unresolved discussions (waiting on @corbin-chris and @mattgarner)

___
*[`dxapp.json` line 16 at r1](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/2#-NHOuox_8Bc1yg3d_ntf:-NHOuox_8Bc1yg3d_ntg:b1x3614) ([raw file](https://github.com/eastgenomics/eggd_starfusion/blob/d87363a73b2a68e1d26bda4e685dd41c29e2c113/dxapp.json#L16)):*
> ```JSON
>       "help": "Chimeric junction files, produced by STAR-Aligner",
>       "class": "file",
>       "patterns": ["*.chimeric.out.junction", "*.chimeric.junction.out"],
> ```

STAR aligner outputs the junction files as `${sample_name}.chimeric.out.junction` so STAR fusion should only need to take that name format as an input
___
*[`README.md` line 27 at r1](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/2#-NHOwPolBeQJ96oHkce4:-NHOwPolBeQJ96oHkce5:bilsjf) ([raw file](https://github.com/eastgenomics/eggd_starfusion/blob/d87363a73b2a68e1d26bda4e685dd41c29e2c113/README.md#L27)):*
> ```Markdown
>     * starfusion_predictions: the predictions file prefixed with the sample name (extracted from the StarAligner junctions file), and ending '.fusion_predictions.tsv'
>     * starfusion_abridged: the abridged version of the predictions file, prefixed with the sample name (as above),
>     and ending '.fusion_predictions.abridgedtsv'
> ```

add dot so it reads:
.fusion_predictions.abridged.tsv



_Code quote:_
```Markdown
.fusion_predictions.abridgedtsv
```
___
*[`README.md` line 105 at r1](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/2#-NHOwAVACtGTEH1yGsOP:-NHOwAVACtGTEH1yGsOQ:b-msdcno) ([raw file](https://github.com/eastgenomics/eggd_starfusion/blob/d87363a73b2a68e1d26bda4e685dd41c29e2c113/README.md#L105)):*
> ```Markdown
> 
> ## Notes
> * This app is not ready for production use
> ```

Maybe remove this as it will need to be removed when its in use

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/2)* status: all files reviewed, 3 unresolved discussions (waiting on @kjwinfield and @mattgarner)

___
*[`dxapp.json` line 16 at r1](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/2#-NHOuox_8Bc1yg3d_ntf:-NHPGoFH3YurnDYNcBW-:b3opzi8) ([raw file](https://github.com/eastgenomics/eggd_starfusion/blob/d87363a73b2a68e1d26bda4e685dd41c29e2c113/dxapp.json#L16)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

STAR aligner outputs the junction files as `${sample_name}.chimeric.out.junction` so STAR fusion should only need to take that name format as an input
</blockquote></details>

Had made it take both formats because of mix-ups in some test file naming, but changed now.
___
*[`README.md` line 105 at r1](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/2#-NHOwAVACtGTEH1yGsOP:-NHPGx-I6Wxobveevn5O:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_starfusion/blob/d87363a73b2a68e1d26bda4e685dd41c29e2c113/README.md#L105)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

Maybe remove this as it will need to be removed when its in use
</blockquote></details>

Done.

**Review by kjwinfield — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mattgarner)

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/2)* status: all files reviewed, 2 unresolved discussions (waiting on @corbin-chris)

___
*[`dxapp.json` line 36 at r2](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/2#-NHUyGdL81arrSDPC6bM:-NHUyGdMDLagidet5ydJ:undefined) ([raw file](https://github.com/eastgenomics/eggd_starfusion/blob/1a202ead7b4239fa044a3e2ee34513931cb64d26/dxapp.json#L36)):*
> ```JSON
>       "name": "opt_parameters",
>       "label": "Optional additional parameters to be used by STAR-Fusion",
>       "help": "The optional additional parameters and flags for STAR-Fusion. Should be space-delimated, and in the format --parameter-name value",
> ```





_Suggestion:_
```JSON
delimited
```
___
*[`README.md` line 4 at r2](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/2#-NHUy_1m62xOyx8NHtUV:-NHUy_1m62xOyx8NHtUW:b1z0py3) ([raw file](https://github.com/eastgenomics/eggd_starfusion/blob/1a202ead7b4239fa044a3e2ee34513931cb64d26/README.md#L4)):*
> ```Markdown
> 
> ## What does this app do?
> Runs STAR-Fusion v1.11.1, a tool which identifies candidate fusion transcripts from RNA alignments. This app is specifically set up to process the 'Chimeric.out.junction' files produced by the earlier STAR-Aligner alignment step. It produces files of candidate fusion regions.
> ```

Does it specifically run only v1.11.1, or whatever is in the docker image you pass to it?



_Code quote:_
```Markdown
STAR-Fusion v1.11.1
```

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/2)* status: all files reviewed, 2 unresolved discussions (waiting on @mattgarner)

___
*[`dxapp.json` line 36 at r2](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/2#-NHUyGdL81arrSDPC6bM:-NHV4ZnW0BRncBy4lu_m:bc5a45h) ([raw file](https://github.com/eastgenomics/eggd_starfusion/blob/1a202ead7b4239fa044a3e2ee34513931cb64d26/dxapp.json#L36)):*
> ```JSON
>       "name": "opt_parameters",
>       "label": "Optional additional parameters to be used by STAR-Fusion",
>       "help": "The optional additional parameters and flags for STAR-Fusion. Should be space-delimated, and in the format --parameter-name value",
> ```

Oops! Done.
___
*[`README.md` line 4 at r2](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/2#-NHUy_1m62xOyx8NHtUV:-NHV4znv-5R7TRAwl2uH:b-twfw29) ([raw file](https://github.com/eastgenomics/eggd_starfusion/blob/1a202ead7b4239fa044a3e2ee34513931cb64d26/README.md#L4)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Does it specifically run only v1.11.1, or whatever is in the docker image you pass to it?
</blockquote></details>

Good point. Removed and explained that it runs a Docker image.

**Review by corbin-chris — COMMENTED** [review]
Think this is done now?

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/2#-:-NHjKlPO1stIvxL8FbLZ:b-wjpfhc)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @kjwinfield and @mattgarner)

**Review by mattgarner — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbin-chris)

**Pull request merged**
