### PR TITLE
Sf v1.11.1 dev

### PR DESCRIPTION
**Pull request by corbin-chris**
**221102 Pre-review information**
_Summary_
This app runs STAR-Fusion, a tool which identifies candidate fusion transcripts from RNA alignments. This app is specifically set up to process the 'Chimeric.out.junction' files produced by the earlier STAR-Aligner alignment step. It produces files of candidate fusion regions.

__Demonstration__
The app was run in the following job:
https://platform.dnanexus.com/projects/GGfqfKQ4Y6YpVyxZ8j6QgBJx/monitor/job/GJV9k0Q4Y6YV0fQf4J57P9g3

Using this applet (though NB this gets overwritten when changes are made):
applet-GJV8yG04Y6Yx08ZK3Gj6PJfF

The app was run as follows:
```
dx run project-GGfqfKQ4Y6YpVyxZ8j6QgBJx:/eggd_starfusion \
-ijunction=file-GJJPZvQ42QQQpjzX90Z3ZG1b \
-isf_docker=file-GGygFkQ4Y6Yjp0jpBjgV9VZx \
-igenome_lib=file-GFq2PJ846G2F120Y80qFVJQb
```

It produced the following output files (found in project-GGfqfKQ4Y6YpVyxZ8j6QgBJx):
file-GJVBKfQ4YF8XYXvGGJ6BzB0k
file-GJVBKfQ4YF8Zf5g3F9Qxvj7j

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/1)

### CODE REVIEW

**Review by kjwinfield — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/1)* status: all files reviewed, 4 unresolved discussions (waiting on @corbin-chris and @mattgarner)

___
*[`dxapp.json` line 3 at r2](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/1#-NFwtnhiA4KSAsM7ChIl:-NFwtnhiA4KSAsM7ChIm:b-41v1el) ([raw file](https://github.com/eastgenomics/eggd_starfusion/blob/c890c3195d327c6364b42184067f95da70851ee5/dxapp.json#L3)):*
> ```JSON
> {
>   "name": "starfusion_v1.11.1",
>   "title": "STAR-Fusion v1.0.0",
> ```

this could just be me not understanding - but why are these version numbers different?



_Code quote:_
```JSON
  "name": "starfusion_v1.11.1",
  "title": "STAR-Fusion v1.0.0",
```
___
*[`dxapp.json` line 28 at r2](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/1#-NFwtQNdCgp2Ceb3_MKy:-NFwtQNdCgp2Ceb3_MKz:b-1sokug) ([raw file](https://github.com/eastgenomics/eggd_starfusion/blob/c890c3195d327c6364b42184067f95da70851ee5/dxapp.json#L28)):*
> ```JSON
>       "name": "genome_lib",
>       "label": "genome_lib",
>       "help": "STAR genome resources",
> ```

maybe could be more specific about what this is?



_Code quote:_
```JSON
"STAR genome resources",
```
___
*[`README.md` line 1 at r2](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/1#-NFwu72wDfq29kXewvDa:-NFwu72wDfq29kXewvDb:bs0pzfq) ([raw file](https://github.com/eastgenomics/eggd_starfusion/blob/c890c3195d327c6364b42184067f95da70851ee5/README.md#L1)):*
> ```Markdown
> # STAR-Fusion v1.0.1
> ```

this doesn't match the version in the dxapp.json



_Code quote:_
```Markdown
v1.0.1
```
___
*[`src/code.sh` line 13 at r2](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/1#-NFwsfwr9rrf1zBpcjvj:-NFwsfwr9rrf1zBpcjvk:br9ye2h) ([raw file](https://github.com/eastgenomics/eggd_starfusion/blob/c890c3195d327c6364b42184067f95da70851ee5/src/code.sh#L13)):*
> ```Shell
> 
> # make output dirs for later
> mkdir /home/dnanexus/out
> ```

you could cut this and then just have:



_Code snippet:_
```Shell
mkdir -p /home/dnanexus/out/starfusion_predictions
mkdir /home/dnanexus/out/starfusion_abridged
```

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/1)* status: all files reviewed, 4 unresolved discussions (waiting on @kjwinfield and @mattgarner)

___
*[`dxapp.json` line 3 at r2](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/1#-NFwtnhiA4KSAsM7ChIl:-NGQhs1a53no0yPbdAiJ:b-a7rg9x) ([raw file](https://github.com/eastgenomics/eggd_starfusion/blob/c890c3195d327c6364b42184067f95da70851ee5/dxapp.json#L3)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

this could just be me not understanding - but why are these version numbers different?
</blockquote></details>

This was me getting confused because it's version v1.11.1 of STAR-Fusion, but version v1.0.0 of the DNA Nexus app which runs STAR-Fusion. I'll change it to 'eggd_starfusion' in line with other projects, and added version to another JSON field instead.
___
*[`dxapp.json` line 28 at r2](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/1#-NFwtQNdCgp2Ceb3_MKy:-NGQi863C6vhLFHCU5kf:befy6kd) ([raw file](https://github.com/eastgenomics/eggd_starfusion/blob/c890c3195d327c6364b42184067f95da70851ee5/dxapp.json#L28)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

maybe could be more specific about what this is?
</blockquote></details>

Will add better explanation.
___
*[`README.md` line 1 at r2](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/1#-NFwu72wDfq29kXewvDa:-NGQjApP7gp0Y0jpiAhE:b-bqivcu) ([raw file](https://github.com/eastgenomics/eggd_starfusion/blob/c890c3195d327c6364b42184067f95da70851ee5/README.md#L1)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

this doesn't match the version in the dxapp.json
</blockquote></details>

Will fix.
___
*[`src/code.sh` line 13 at r2](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/1#-NFwsfwr9rrf1zBpcjvj:-NGQkQmFCejAXZhxiUUi:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_starfusion/blob/c890c3195d327c6364b42184067f95da70851ee5/src/code.sh#L13)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

you could cut this and then just have:
</blockquote></details>

Done.

**Review by mattgarner — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/1)* status: all files reviewed, 4 unresolved discussions (waiting on @kjwinfield)

**Review by kjwinfield — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_starfusion/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbin-chris)

**Pull request merged**
